version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${PRODUCTION}
      - PORT=${PORT}
      - URI=mongodb://mongodb:27017/alumni_portal
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - EMAIL_HOST=${EMAIL_HOST}
      - JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET}
    depends_on:
      - mongodb
    volumes:
      - public_files:/app/public
      - ${PWD}/uploads:/app/uploads
    networks:
      - alumni-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - alumni-network
    restart: unless-stopped

networks:
  alumni-network:
    driver: bridge

volumes:
  mongodb_data:
  public_files: